export function generateMarkdownReport({
  repoName,
  views,
  clones,
  referrers,
  paths,
  languages,
  openIssues,
  openPulls
}: {
  repoName: string;
  views: any;
  clones: any;
  referrers: any[];
  paths: any[];
  languages: Record<string, number>;
  openIssues: number;
  openPulls: number;
}) {
  const date = new Date().toLocaleDateString();
  
  let md = `# Traffic & Health Report: ${repoName}\n`;
  md += `*Generated on: ${date}*\n\n`;

  md += `## 📊 Executive Summary\n`;
  md += `- **Total Views (14d)**: ${views?.count || 0} (${views?.uniques || 0} unique)\n`;
  md += `- **Total Clones (14d)**: ${clones?.count || 0} (${clones?.uniques || 0} unique)\n`;
  md += `- **Open Issues**: ${openIssues}\n`;
  md += `- **Open Pull Requests**: ${openPulls}\n`;
  
  if (views?.uniques && clones?.uniques) {
    const conversion = Math.round((clones.uniques / views.uniques) * 100);
    md += `- **Clone Conversion Rate**: ${conversion}%\n`;
  }
  md += `\n`;

  if (languages && Object.keys(languages).length > 0) {
    md += `## 💻 Language Composition\n`;
    for (const [lang, bytes] of Object.entries(languages)) {
      md += `- **${lang}**: ${bytes} bytes\n`;
    }
    md += `\n`;
  }

  if (referrers && referrers.length > 0) {
    md += `## 🔗 Top Referrers\n`;
    md += `| Referrer | Views | Unique Visitors |\n`;
    md += `| :--- | :---: | :---: |\n`;
    for (const ref of referrers.slice(0, 10)) {
      md += `| ${ref.referrer} | ${ref.count} | ${ref.uniques} |\n`;
    }
    md += `\n`;
  }

  if (paths && paths.length > 0) {
    md += `## 📄 Popular Paths\n`;
    md += `| Path | Views | Unique Visitors |\n`;
    md += `| :--- | :---: | :---: |\n`;
    for (const path of paths.slice(0, 10)) {
      const cleanTitle = (path.title || path.path).replace(/\|/g, '-');
      md += `| ${cleanTitle} | ${path.count} | ${path.uniques} |\n`;
    }
    md += `\n`;
  }

  md += `---\n`;
  md += `*Generated by GitHub Traffic Manager*\n`;

  return md;
}

export function downloadMarkdown(filename: string, content: string) {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', `${filename}.md`);
  document.body.appendChild(link);
  link.click();
  
  // Cleanup
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
